### ISSUE TITLE
Areas with no code coverage

### ISSUE THREAD

**Issue by gowerc** [insightsengineering/rbmi#109]
mcmc  same_cov = FALSE
impute with data$update_strategies(update_strategy)
analyse( delta)
extract_imputed_df(idmap)
prepare_data_mcmc (  ! saame_cov)
expand_locf
strategy_JR ( mar = all rows )
strategy_JR( mar = no rows)

**Comment by nociale** [comment]
@gowerc Are we missing any of these items?

**Comment by gowerc** [comment]
I think with the tests I just added and with the nightly tests all of these are covered now
