### ISSUE TITLE
Do `draws` and `impute` work if the user does not specify `data_ice`?

### ISSUE THREAD

**Issue by nociale** [insightsengineering/rbmi#157]
@gowerc I am wondering whether we should set a default value (like `data_ice = NULL`) and the behavior is that we assume MAR for any observation in the dataset. Currently, is that right that if the user explicitly specifies `data_ice = NULL` then everything is assumed to be MAR? Do we want to set this as a default value in `draws` and `impute`?

**Comment by gowerc** [comment]
Is that not the current behaviour ? Or does it error when data_ice is missing ?  I think I agree that allowing data_ice to be null should be allowed and should assume everything is MAR.  Though this may add complications with the "is_post_ice" flag in the delta datasets.... though I'd need to refresh myself on what the logic is there

**Comment by nociale** [comment]
I honestly don't know whether it currently works. "is_post_ice" should be `FALSE` for any entry in this case I guess?
