### ISSUE TITLE
Add more references

### ISSUE THREAD

**Issue by gowerc** [insightsengineering/rbmi#179]
Need to check with @wolbersm  but was mentioned in our last catch up that we should include links to more of the reference papers

**Comment by gowerc** [comment]
@nociale  & @wolbersm  What were the main references that we were missing / needed to add again sorry ?

**Comment by wolbersm** [comment]
@gowerc I have just added some key refs to draws() and impute() and created pull requests for @nociale.

**Comment by gowerc** [comment]
Thank you.
