### ISSUE TITLE
optim referencing issue

### ISSUE THREAD

**Issue by gowerc** [insightsengineering/rbmi#203]
cmdcheck is throwing the following note:

```
❯ checking Rd cross-references ... NOTE
  Unknown package ‘optim’ in Rd xrefs
```

This likely means we have a referencing issue  likely we have `[otim::function()]` or [optim()]` somewhere instead of `[stats::optim()]`

**Comment by nociale** [comment]
@gowerc It was in draws, my fault. I just solved it and pushed in the update_doc_files branch.
