### ISSUE TITLE
Include code of antidepressant trial download and pre-processing

### ISSUE THREAD

**Issue by nociale** [insightsengineering/rbmi#205]
@gowerc I don't manage to make a code to download the antidepressant trial in order to show the pre-processing code. I could download it, save it internally in the package, pre-process it and save it as a RData file but I guess this is not optimal as we will have a `sas7bdat` and a `RData` files which contain essentially the same data.

**Comment by gowerc** [comment]
you definitely don't need to store the sas7bdat.  What is the URL that you downloaded it from I can provide an example script of what I mean.

**Comment by nociale** [comment]
@gowerc The dataset can be downloaded here: [](https://www.lshtm.ac.uk/research/centres-projects-groups/missing-data#dia-missing-data) (end of the page).

**Comment by gowerc** [comment]
The following should do most of what you need (you do not need to include any of the libraries into the description file as this is a pure utility script and is never really intended to be run)

```
# install.packages("httr")
# install.packages("haven")

library(httr)
library(haven)

### URL to download the zip file from
link <- "https://lshtm.sharepoint.com/sites/MissingDataPublicFiles/_layouts/15/download.aspx?SourceUrl=%2Fsites%2FMissingDataPublicFiles%2FShared%20Documents%2Ffiles%5Ffor%5Fsharepoint%2FExample%5Fdata%5Fsets%2Fantidepressant%2FMBSW2011%5Fexample%2Ezip"

### Grab the files binary contents
resp <- GET(link)
x <- content(resp, type = "raw")


### Save zip file to a temporary directory
tdir <- tempdir()
tfile <- file.path(tdir, "temp.zip")
tmp <- file(tfile, raw = TRUE, open='w+b')
writeBin(x, tmp)
close.connection(tmp)

### Extract zip file
unzip(zipfile = tfile,  overwrite= TRUE, exdir = tdir)

### Identify extracted sas dataset
sasfile <- list.files(tdir, pattern = "sas7bdat$", full.names = TRUE)

### Import sas dataset into R
read_sas(sasfile)

```
