### ISSUE TITLE
Difference between file name and file title results in a warning in vignette

### ISSUE THREAD

**Issue by nociale** [insightsengineering/rbmi#207]
@gowerc We might want to avoid this check:

`options(rmarkdown.html_vignette.check_title = FALSE)`. Where should we put this code?

**Comment by gowerc** [comment]
Sorry whats the reasoning for this, as in whats the issue that this solves ?

**Comment by nociale** [comment]
I don't know if this can result in a warning when checking the package? If not, then I am happy to close this issue :)
