### ISSUE TITLE
bookdown dependancy

### ISSUE THREAD

**Issue by nociale** [insightsengineering/rbmi#208]
@gowerc The statistical specifications vignette requires dependancy on `bookdown` package for cross-references (as described [here](https://bookdown.org/yihui/rmarkdown-cookbook/cross-ref.html)). The check of the package fails because of this.

Moreover, is it correct to put bookdown in the Suggests packages in the DESCRIPTION file? The vignette also makes use of the packages `knitr` and `kableExtra`. How should they be handled?

**Comment by gowerc** [comment]
Anything relating to vignettes should go into the suggests. If you give me a complete list of packages I can add them to the cicd build image.  That being said are all those packages really needed ? I am suprised that bookdown and kableExtra are needed ? What functionality from them are you using that isn't provided by base knitr / rmarkdown ?

**Comment by nociale** [comment]
`bookdown` is needed for cross-referencing, e.g. to say "this is described in section 1.2". The other two packages, I am not sure they are needed and I will investigate them. `bookdown` is already in the suggests of the description file

**Comment by nociale** [comment]
@gowerc I checked and to me it seems that only `bookdown` is necessary. I removed the dependancy on kableExtra

**Comment by gowerc** [comment]
I have updated the image to include bookdown this should be resolved now. Feel free to re-open if it is not
