### ISSUE TITLE
Allow Rubin's rules to work in case of `se = NA`?

### ISSUE THREAD

**Issue by nociale** [insightsengineering/rbmi#226]
Sometimes one might want to get point estimates without SE estimation. 

For example, for a responder analysis the analysis model might be a logistic regression for a dichotomized endpoint. One might additionally want the estimated proportion of responders in the two groups and not just the adjusted difference between them in log-odds scale, which is a regression coefficient in the logistic regression used to study significance but not easily interpretable.

This could be done by simply allowing the (user-defined) analysis model to return `se = NA` for the proportions parameters. The pooling function should simply in this case return `NA` for SE, CIs and p-value but still return the pooled point estimate.

**Comment by gowerc** [comment]
In these instances though why would you not want the SE estimate ?
