### ISSUE TITLE
Improvements of advanced vignette

### ISSUE THREAD

**Issue by nociale** [insightsengineering/rbmi#229]
- [x]  Use the improved data simulation function as per #225 
- [x] Better description and summary of when changing imputation strategy in `impute()` is allowed
- [x] Add section of example of usage with time-varying covariates. Show that MAR imputation here is equivalent to CIR imputation without time varying covariates (assuming post-ICE data are simulated according to CIR trajectory). Keep using Bayes as done in the rest of the vignette or condmean imputation?
- [x] Include realistic delta adjustement and tipping point analysis (look at Cro et al examples)

**Comment by wolbersm** [comment]
Hi @nociale 

Sounds good. As we discussed, below a suggestion for the full structure of the updated advanced vignette (duplicating in part what you wrote):

- [ ] Simulate "realistic" data with a single ICE using the improved simulation function (simulating post-ICE data using CIR)
- [ ] Illustrate imputation using CIR & quasi-Bayesian MI (main estimate; this is already shown in the basic vignette; only thing new here is that the data includes post-ICE data)
- [ ] Show how to change the imputation strategy in impute() with caveats for changing from MAR <-> ref-based
- [ ] Show how to perform a realistic delta adjustment and tipping point analysis (see e.g. Cro tutorial for motivation)
- [ ] Illustrate imputation based on MAR + time-varying covariate ("instead" of CIR)
- [ ] Show how to change the analysis function (with caveats for conditional mean imputation). I suggest to change the analysis to binary (change at last visit > threshold) as in the current version.

**Comment by nociale** [comment]
@gowerc everything we wanted to include from the latest discussions has been included. So we can close this now.
