### ISSUE TITLE
Implementation of method type="BMLMI" - bootstrapped ML MI as in van Hippel & Bartlett

### ISSUE THREAD

**Issue by wolbersm** [insightsengineering/rbmi#233]
Method is described in van Hippel & Bartlett, Stat Sci 2021 article also available at [https://arxiv.org/pdf/1210.0870.pdf](https://arxiv.org/pdf/1210.0870.pdf).
The methods is based on analyzing D randomly imputed datasets (imputation uses the ML/REML estimator) for each of B bootstrap samples. Estimates are then pooled across the B*D datasets and variance is estimated as per section 8 of the manuscript. 

This is less efficient than using conditional mean imputation for ANCOVA as the analysis method but has the advantage to also be theoretically valid (in the sense of giving correct frequentist inference) for other analysis models.

**Comment by nociale** [comment]
@gowerc @wolbersm 
We can include this method as follows:

- set-up a new `method`: 
   ``` method_bootRand(
  covariance = c("us", "toep", "cs", "ar1"),
  threshold = 0.01,
  same_cov = TRUE,
  REML = TRUE,
  B = 20,
  D = 2
) ```

1. `draws()` returns parameter estimates for B bootstrap samples (internally, we just call `get_bootstrap_samples()` and we keep the sampled ids for each sample).
2. `impute()` will impute randomly D times each bootstrap sample.
3. `analyse()` will analyse each of the B*D imputed dataset (no need to add anything).
4. `pool()` will pool the results as explained in section 8 of the mentioned paper.

Alternatively, we can notice that step 1 (i.e. the call to `draws()`) is exactly the same as if I called `draws()` for `method_condmean(type = "bootstrap")`. So the user could simply make this call and then set random imputations later (currently not supported). As user I maybe won't feel comfortable to make this type of procedure (call a "condmean method") if I want to implement a method with random imputation. So my preference is for the first alternative.

Secondary questions: 

- Do we want to keep the `threshold` argument for this method? This threshold would then be related only to `B`.
-  Nice name for this method? `method_randBoot` or `method_bootRand` or...?

**Comment by wolbersm** [comment]
@nociale 
Thanks a lot. Sounds all good to me. My 2c on your questions:

- I agree it's cleaner to set up a new method. 
- I would keep the threshold argument (referring only to B as you write). 
- I like method_bmlmi best as this is also how van Hippel and Bartlett call it.

**Comment by nociale** [comment]
- [ ] Implement method
- [ ] Add testing
- [ ] Modify documentation
- [ ] Explain or mention method in stats specs vignette

**Comment by nociale** [comment]
@gowerc I am wondering what is the best way of implementing this method in `impute()`. 

In terms of efficiency, the best would be to simply modify within `impute_data_individual()` and allow to call `impute_outcome()` D times. This would randomly sample multiple times using the same `conditional_parameters`. However this creates a problem in `extract_imputed_df()` in the `analyse()` phase, so it would require to modify also `extract_imputed_df()`.

Alternatively, we can modify this 

```
imputes <- mapply(
        impute_data_individual,
        names(samples_grouped$index),
        samples_grouped$index,
        MoreArgs = list(
            beta = samples_grouped$beta,
            sigma = samples_grouped$sigma,
            data = data,
            references = references,
            strategies = strategies,
            condmean = condmean
        ),
        SIMPLIFY = FALSE
    )
```
to something like 

```
imputes <- sapply(seq.int(D), function(x) mapply(
        impute_data_individual,
        names(samples_grouped$index),
        samples_grouped$index,
        MoreArgs = list(
            beta = samples_grouped$beta,
            sigma = samples_grouped$sigma,
            data = data,
            references = references,
            strategies = strategies,
            condmean = condmean
        ),
        SIMPLIFY = FALSE
    )
)
```
but then there would be other problems later (e.g. in `untranspose_imputations()`. This second option is also less efficient in my opinion, since we calculate the same conditional parameters multiple times.

What do you think?

**Comment by gowerc** [comment]
@nociale  & @wolbersm ,  Can I clarify what formula we should be using for the point estimate as there appears to be multiple in that paper my guess would be this one ? 

![image](https://user-images.githubusercontent.com/8447209/143229866-97fba114-6764-41b9-b3e9-1ba2674fc0ac.png)

**Comment by wolbersm** [comment]
@gowerc 
Yes, we are doing boostrapped MLMI (BMLMI) here and I agree this is the right estimate.
![image](https://user-images.githubusercontent.com/90774360/143231148-ce40a2ef-55f7-43df-af6f-c0a77ddaaa65.png)
