### ISSUE TITLE
Allow for changing covariance structure for initializing MCMC and set prior parameter in `method_bayes()` 

### ISSUE THREAD

**Issue by nociale** [insightsengineering/rbmi#234]
Allow the user to specify a different covariance structure for the MMRM model needed to initialize the fit of the base imputation model using a Bayesian approach. The base imputation model still assumes an unstructured covariance structure, but the MMRM could also be fit using a simpler one. This might be useful when MMRM on the original dataset fails and an error is thrown prior to the MCMC start. In this case, the user could set a simpler covariance structure for MMRM (but not for the MCMC) using, e.g. `method_bayes(..., init_cov = "ar1")`. `method$init_cov` is a parameter that takes the same values as `method$covariance`, but can be specified only for `method_bayes()` and has default value to `"us"`.  By setting `init_cov` differently from `'us'` the user will (1) provide starting values of the MCMC equal to MMRM estimates with simpler covariance structure, and (2) assume that the prior for the covariance matrix is a inverse-wishart distribution with mean equal to a non-unstructured covariance matrix. .

**Comment by nociale** [comment]
@gowerc What do you think? :) I could implement this easily but I would like your opinion on this before.

**Comment by gowerc** [comment]
Does this not have a complication with the burn in ? 

Like atm our diagnositics are quite light and we have very small burn in under the assumption that we are starting in the middle of the MLE however this would violate that assumption no ?

Also I am just a bit concerned that users might confuse this to mean that they are specifying the covariance structure of the overall model not just the initial one.  I duno I'm not overall happy of the idea; my general mentality is that convergence issues on the full data that there is likely to be something wrong with the overall dataset and that these sorts of bandaids just attempt to hide it.

**Comment by nociale** [comment]
Ok, we decide not to implement this feature.
