### ISSUE TITLE
Review LSmeans implementaiton

### ISSUE THREAD

**Issue by gowerc** [insightsengineering/rbmi#275]
Potentially a need for lsmeans to be weighted by data prevalenance

i.e. 
    1. calculate prediction for entire dataset setting treatment to "placebo"
    2. calculate mean of this prediction
    3. calculate prediction for entire dataset setting treatment to "active"
    4. calculate mean of this prediciton

**Comment by gowerc** [comment]
@wolbersm  & @nociale ,  Sorry just to confirm were we all in agreement that this should be the default LSmeans implementation? 

I just wanted to tripple check because it would mean we are deviating from the SAS default which teams currently use (at least that was my understanding)

**Comment by wolbersm** [comment]
Yes, I think so. When phrasing this in terms of "standard LSMEANS language", I think this is the same as evaluating the predicted mean based one the treatment group and the all the design matrix for all other covariates fixed to their means.
Could you please cross-check this gives the same as SAS or emmeans weighted by data prevalence.
