### ISSUE TITLE
Unit tests fail on Mac M1

### ISSUE THREAD

**Issue by gowerc** [insightsengineering/rbmi#326]
══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure (test-pool.R:101:5): get_ests_bmlmi ─────────────────────────────────
  ... & res$est_point == mean(ests) is not TRUE
  
  `actual`:   FALSE
  `expected`: TRUE 
  
  [ FAIL 1 | WARN 0 | SKIP 11 | PASS 1085 ]

**Comment by Polkas** [comment]
main branch:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/10676545/156613306-7a529bca-ec02-419c-b63b-855a429c4d86.png">
fix-rcmdcheck branch:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/10676545/156613716-6e856165-a1b3-4215-9c24-5774b22c0a41.png">
