### ISSUE TITLE
`ld$get_data(na.rm=TRUE)` only appears to work if `nmar.rm=TRUE` as well

### ISSUE THREAD

**Issue by gowerc** [insightsengineering/rbmi#347]
Example:

```
visits <- c("V", "I", "S", "T")

dat <- tibble(
    pt = factor(c("A", "A", "A", "A", "B", "B", "B", "B"), levels = c("A", "B")),
    vis = factor(rep(visits, 2), levels = visits),
    out = c(NA, 4, NA, 3, 6, NA, 1, NA),
    group = factor(c("G", "G", "G", "G", "F", "F", "F", "F"), levels = c("G", "F")),
    age = rnorm(8)
)

vars <- set_vars(
    outcome = "out",
    visit = "vis",
    subjid = "pt",
    group = "group",
    covariates = c("age"),
    strategy = "strategy"
)

ld <- longDataConstructor$new(dat, vars)

> ld$get_data(na.rm = TRUE)
  pt vis out group         age
1  A   V  NA     G -0.46663159
2  A   I   4     G  1.68595984
3  A   S  NA     G -0.56792093
4  A   T   3     G -0.04674302
5  B   V   6     F -0.15698059
6  B   I  NA     F  1.60224244
7  B   S   1     F  0.76865367
8  B   T  NA     F -0.77162936
```

I would have expected all the missing observations to have been removed ? 

Scanning over the code though I'm struggling to remember what we wanted this argument to acheive as it only seems to be used twice both times in tandem with `nmar.rm`:

draws.R L420
```
    dat <- longdata$get_data(ids, nmar.rm = TRUE, na.rm = TRUE)
```

draws.R L466
```
    data <- longdata$get_data(longdata$ids, nmar.rm = FALSE, na.rm = FALSE)
```

Considering `na.rm=TRUE` is not actively used anywhere I propose we just remove it in favour of nmar.rm

**Comment by gowerc** [comment]
@nociale 

Ok, just remembered, both arguments are needed because the `nmar.rm` will also remove observed values that occur after a NMAR ICE  where as `na.rm` only removes missing values. Doing some light testing this is all working as expected but will add some unit tests as we seem to be quite light on them here....

That being said there appears to be a "bug"  in that neither  `nmar.rm` nor `na.rm` work if no patient  ID's are provided.  This is never used anywhere but I am thinking it might be worth fixing just to avoid any unexpected complications in the future if someone does try to use this functionality.

**Comment by nociale** [comment]
Yes, `nmar.rm` would remove non-MAR data regardless of whether they are observed or not. Since `nmar.rm` and `na.rm` do different things, I agree we should keep them, even if currently we don't use all the possible combinations. 

I agree that it does not make too much sense that if no patient ID's are provided, then it just does nothing. If there was no particular logic why it should do this, then we better change it.

**Comment by gowerc** [comment]
I think the original rationale for this was efficiency i.e. if you are calling `get_data()` without ids chances are you just want the full dataset so it short cuts any additional processing. But yer I think this is just highly confusing and could risk bugs in the future so will update anyway
