### ISSUE TITLE
Not found-fit_mmrm function in  rbmi library

### ISSUE THREAD

**Issue by osamaidais** [insightsengineering/rbmi#351]
I have installed the library rbmi on my R studio, but the function fit_mmrm is not found. 
How could I solve this issue?

thanks

**Comment by gowerc** [comment]
Hey @osamaidais ,

Would you mind sharing the exact code you are running to see this error. If you could also share a screenshot of the exact error message as well that would be super useful thank you.

**Comment by osamaidais** [comment]
`#This is my code


#install.packages("rbmi")
library("rbmi")

library("MASS") 
library("foreach")
library("rWishart")
library("corpcor")
library(MASS)

n_0=500
trg=4 # number of treatments arms: tr0', 'trt1', 'trt2', 'trt3'
timepoints=5 # '0.5', '1', '2', '3','4'
size=trg*n_0#
N=size*timepoints
sigma1=c(11.5)
sigma2=c(12)
sigma3=c(13)
sigma4=c(14)
sigma5=c(15)
i=1
p_tr1<-c()
p_tr2<-c()
p_tr3<-c()
min_p<-c()
max_p<-c()
set.seed(1232)
corrs=matrix(c(1.00, 0.69, 0.48, 0.45, 0.42,
               0.69, 1.00, 0.74, 0.71, 0.65, 
               0.48, 0.74, 1.00, 0.78, 0.73,
               0.45, 0.71, 0.78, 1.00, 0.82,
               0.42, 0.65, 0.73, 0.82, 1.00),
             5,5)
COV_times=matrix(c(sigma1^2, 0.69*sigma1*sigma2, 0.48*sigma1*sigma3, 0.45*sigma1*sigma4, 0.42*sigma1*sigma5,
                   0.69*sigma2*sigma1, sigma2^2, 0.74*sigma2*sigma3, 0.71*sigma2*sigma4, 0.65*sigma2*sigma5, 
                   0.48*sigma3*sigma1, 0.74*sigma3*sigma2, sigma3^2, 0.78*sigma3*sigma4*4, 0.73*sigma3*sigma5,
                   0.45*sigma4*sigma1, 0.71*sigma4*sigma2, 0.78*sigma4*sigma3, sigma4^2, 0.82*sigma4*sigma5,
                   0.42*sigma5*sigma1, 0.65*sigma5*sigma2, 0.73*sigma5*sigma3, 0.82*sigma5*sigma4, sigma5^2),
                 5,5)

COV_times3=matrix(c(sigma1^2,            0.6937*sigma1*sigma2, 0.4824*sigma1*sigma3,  0.4521*sigma1*sigma4,    0.4762*sigma1*sigma5,
                    0.6937*sigma2*sigma1, sigma2^2,             0.7379*sigma2*sigma3,  0.7146*sigma2*sigma4,    0.7211*sigma2*sigma5, 
                    0.4824*sigma3*sigma1, 0.7379*sigma3*sigma2, sigma3^2,              0.9069*sigma3*sigma4*4,  0.8363*sigma3*sigma5,
                    0.4521*sigma4*sigma1, 0.7146*sigma4*sigma2, 0.9069*sigma4*sigma3,  sigma4^2,                0.9180*sigma4*sigma5,
                    0.4762*sigma5*sigma1, 0.7211*sigma5*sigma2, 0.8363*sigma5*sigma3,  0.9180*sigma5*sigma4,    sigma5^2),
                  5,5)

d=make.positive.definite (COV_times)

#-----------------------------------------------------------------
#tr0
#-----------------------------------------------------------------
y_tr0=mvrnorm(n=n_0, mu=c(-2.5,-3.2,-3.8,-4.7,-5), Sigma=d)


drp_tr0=c(0.08, 0.08,0.16,0.16,0.24)
v_0.5<-1*(runif(n_0)<drp_tr0[1]) # if a uniform random var < dropout rate then missing
v_1<-1*(runif(n_0)<drp_tr0[2])
v_1[v_0.5==1]<-1
v_2<-1*(runif(n_0)<drp_tr0[3])
v_2[v_1==1]<-1
v_3<-1*(runif(n_0)<drp_tr0[4])
v_3[v_2==1]<-1
v_4<-1*(runif(n_0)<drp_tr0[5])
v_4[v_3==1]<-1

y_tr0[,1][v_0.5==1]<-NA
y_tr0[,2][v_1==1]<-NA
y_tr0[,3][v_2==1]<-NA
y_tr0[,4][v_3==1]<-NA
y_tr0[,5][v_4==1]<-NA

t=1
y_tr02=c()
for(t in 1: n_0)
{
  y_tr02=c(y_tr02,y_tr0[t,])
}
#-----------------------------------------------------------------
#tr1
#-----------------------------------------------------------------
y_tr1=mvrnorm(n =n_0, mu=c(-5,-6.2,-8.35,-11,-13.25), Sigma=d)#+


drp_tr1=c(0.04, 0.04,0.08,0.08,0.12)
v_0.5<-1*(runif(n_0)<drp_tr1[1])
v_1<-1*(runif(n_0)<drp_tr1[2])
v_1[v_0.5==1]<-1
v_2<-1*(runif(n_0)<drp_tr1[3])
v_2[v_1==1]<-1
v_3<-1*(runif(n_0)<drp_tr1[4])
v_3[v_2==1]<-1
v_4<-1*(runif(n_0)<drp_tr1[5])
v_4[v_3==1]<-1

y_tr1[,1][v_0.5==1]<-NA
y_tr1[,2][v_1==1]<-NA
y_tr1[,3][v_2==1]<-NA
y_tr1[,4][v_3==1]<-NA
y_tr1[,5][v_4==1]<-NA


t=1
y_tr12=c()
for(t in 1: n_0)
{
  y_tr12=c(y_tr12,y_tr1[t,])
}



#-----------------------------------------------------------------
#tr2
#-----------------------------------------------------------------

y_tr2=mvrnorm(n =n_0, mu=c(-5,-6.2,-8.35,-11,-13.25), Sigma=d)#+

drp_tr2=c(0.04, 0.04,0.08,0.08,0.12)
v_0.5<-1*(runif(n_0)<drp_tr2[1])
v_1<-1*(runif(n_0)<drp_tr2[2])
v_1[v_0.5==1]<-1
v_2<-1*(runif(n_0)<drp_tr2[3])
v_2[v_1==1]<-1
v_3<-1*(runif(n_0)<drp_tr2[4])
v_3[v_2==1]<-1
v_4<-1*(runif(n_0)<drp_tr2[5])
v_4[v_3==1]<-1

y_tr2[,1][v_0.5==1]<-NA
y_tr2[,2][v_1==1]<-NA
y_tr2[,3][v_2==1]<-NA
y_tr2[,4][v_3==1]<-NA
y_tr2[,5][v_4==1]<-NA

t=1
y_tr22=c()
for(t in 1: n_0)
{
  y_tr22=c(y_tr22,y_tr2[t,])
}

#-----------------------------------------------------------------
#tr2
#-----------------------------------------------------------------
y_tr3=mvrnorm(n =n_0, mu=c(-4.5,-5.6,-7.44,-9.74,-11.6), Sigma=d )#+

drp_tr3=c(0.04, 0.04,0.08,0.08,0.12)
v_0.5<-1*(runif(n_0)<drp_tr3[1])
v_1<-1*(runif(n_0)<drp_tr3[2])
v_1[v_0.5==1]<-1
v_2<-1*(runif(n_0)<drp_tr3[3])
v_2[v_1==1]<-1
v_3<-1*(runif(n_0)<drp_tr3[4])
v_3[v_2==1]<-1
v_4<-1*(runif(n_0)<drp_tr3[5])
v_4[v_3==1]<-1

y_tr3[,1][v_0.5==1]<-NA
y_tr3[,2][v_1==1]<-NA
y_tr3[,3][v_2==1]<-NA
y_tr3[,4][v_3==1]<-NA
y_tr3[,5][v_4==1]<-NA
t=1
y_tr32=c()
for(t in 1: n_0)
{
  y_tr32=c(y_tr32,y_tr3[t,])
}

#-----------------------------------------------------------------

#--------------------------------------------------------------------------
#as factors
#--------------------------------------------------------------------------
treat  = factor(
  c(
    rep(c('tr0'), each=n_0*timepoints),
    rep(c( 'tr1'), each=n_0*timepoints),
    rep(c('tr2'), each=n_0*timepoints),
    rep(c('tr3'), each=n_0*timepoints)
  )
)
trttimepoint = factor(rep(c('0.5','1','2','3','4'),size))
#--------------------------------------------------------------------------

#--------------------------------------------------------------------------
#id=seq(1,N,1)
id=factor(rep(seq(1,size,1),each=timepoints))

#response at baseline
bs<-rep(rnorm(size,79,9),each=timepoints)
#vector of all responses
y=c(y_tr02,y_tr12,y_tr22,y_tr32)


#--------------------------------------------------------------------------
#linear model
#--------------------------------------------------------------------------
df= data.frame(id, treat, trttimepoint,bs, y)
df<-within(df, treat <- relevel(treat, ref = 'tr0'))

des.matrix=data.frame(df$bs)
ress<-fit_mmrm(designmat=des.matrix,
               outcome=df$y,
               subjid=as.factor(df$id),
               visit = as.factor(df$trttimepoint),
               group=as.factor(df$treat),
               cov_struct = c("us"),#, "toep", "cs", "ar1"),
               REML = TRUE,
               same_cov = TRUE,
               initial_values = NULL,
               optimizer = "L-BFGS-B"
)

summary(res)

`

**Comment by gowerc** [comment]
Hi @osamaidais,

Apologies would you mind refining your code a bit, I tried to run it but am getting errors from variables that aren't defined anywhere:

```
Error: object 'trgn_0' not found
Error: object 'sizetimepoints' not found
```

**Comment by gowerc** [comment]
@osamaidais ,

Looking at your code though it looks like you are trying to directly call `fit_mmrm()`.  This is an internal function of the package and isn't exported (i.e. we don't explicitly support users using this function). 

If you are wanting to fit a MMRM "by hand" i would recommend just calling the `glmmTMB` package directly (which is what we use under the hood for RBMI).  An example of this fitting an unstructured covariance matrix being:

```
library(glmmTMB)

glmmTMB(
    formula = outcome ~ age + sex + trt + visit + us(0 + visit | pt),
    data = dat,
    dispformula = ~0
)
```

**Comment by osamaidais** [comment]
> Hi @osamaidais,
> 
> Apologies would you mind refining your code a bit, I tried to run it but am getting errors from variables that aren't defined anywhere:
> 
> ```
> Error: object 'trgn_0' not found
> Error: object 'sizetimepoints' not found
> ```

Hi @gowerc 
the multiplicatio is missing, there should be

size=trg*n_0
N=size*timepoints

**Comment by osamaidais** [comment]
> Hi @osamaidais,
> 
> Apologies would you mind refining your code a bit, I tried to run it but am getting errors from variables that aren't defined anywhere:
> 
> ```
> Error: object 'trgn_0' not found
> Error: object 'sizetimepoints' not found
> ```

The multiplication * were missing but now all code lines are updated.

**Comment by osamaidais** [comment]
> @osamaidais ,
> 
> Looking at your code though it looks like you are trying to directly call `fit_mmrm()`. This is an internal function of the package and isn't exported (i.e. we don't explicitly support users using this function).
> 
> If you are wanting to fit a MMRM "by hand" i would recommend just calling the `glmmTMB` package directly (which is what we use under the hood for RBMI). An example of this fitting an unstructured covariance matrix being:
> 
> ```
> library(glmmTMB)
> 
> glmmTMB(
>     formula = outcome ~ age + sex + trt + visit + us(0 + visit | pt),
>     data = dat,
>     dispformula = ~0
> )
> ```

Hi @gowerc 
Thank you for sharing the code glmmTMB. 
Does the term  us(0 + visit | pt) mean that visits repeated withen patients??
what does 0 refer to in us(0 + visit | pt)?
Does this model include randome effect??


my desired model is MMRM with a fixed effect  and with interaction (has no random effect). Would it be possible to run a code like this 
> glmmTMB(
>     formula = outcome ~bs +  treat +  trttimepoint+ us(0 + trttimepoint |id),
>     data = df,
>     dispformula = ~0
> )

**Comment by wolbersm** [comment]
Hi @osamaidais,

The syntax you are questioning is to specify an unstructured covariance structure in glmmTMB, see [https://cran.r-project.org/web/packages/glmmTMB/vignettes/covstruct.html](https://cran.r-project.org/web/packages/glmmTMB/vignettes/covstruct.html). 

Since you appear to be interested in sample size calculations for MMRM, you may also want to have a look at the longPower package [https://cran.r-project.org/web/packages/longpower/index.html](https://cran.r-project.org/web/packages/longpower/index.html) which has a dedicated function `power.mmrm` for this. 

Beware that this page is for issues and questions related directly to the `rbmi` package and, in general, we won't be able to answer questions about other packages here.
