### ISSUE TITLE
Pool F-Values

### ISSUE THREAD

**Issue by MayFine** [insightsengineering/rbmi#365]
Hello,

I am sorry if this is a stupid question. I was wondering how to use the analyze function to do a regular ANCOVA and get pooled F values and degrees of freedom for the model when imputed with `method_bmlmi()`. In `mice `/ `miceadds `I could always use the `mi.anova()` function or `micombine.F()` for this, now I don't know how it behaves with `rmbi `and imputations with von Hippel and Bartlett's method.

Thanks a lot!

**Comment by wolbersm** [comment]
Hello

Thanks for the question. 

Currently, the `analyse()` function only supports pooling of estimates with corresponding standard errors and (if available) degrees of freedom. This is described in described in [section 3.7](https://insightsengineering.github.io/rbmi/articles/stat_specs.html#sec:pooling) of the ["Statistical specifications" vignette](https://insightsengineering.github.io/rbmi/articles/stat_specs.html).

`rbmi` does not currently provide functions for pooling ANCOVA F-values. To implement this yourself, perhaps the easiest would be to extract the multiply imputed datasets using function `extract_imputed_dfs()` and then use the `mice` functions.
