### ISSUE TITLE
Is there an export function to modify the specific variable in `imputeObj`

### ISSUE THREAD

**Issue by kaigu1990** [insightsengineering/rbmi#389]
Hello,

Can I ask if we have an export function to modify the variables in `imputeObj` object like `mutate` process? 
For example, I set the vars in "Draws" procedure but define the `outcome=HAMDTL17` instead of `outcome=CHANGE`.
```
vars <- set_vars(
  outcome = "HAMDTL17",
  visit = "VISIT",
  subjid = "PATIENT",
  group = "THERAPY",
  covariates = c("BASVAL")
)

method <- method_approxbayes(
  covariance = "us"
)

drawObj <- draws(
  data = dat,
  data_ice = dat_ice,
  vars = vars,
  method = method,
  quiet = TRUE
)

imputeObj <- impute(
  drawObj
)
```
And then I get the imputed `imputeObj` object that has complex structure in `imputeObj$imputations`. So it's not easy to modify the variables inside as I only impute the `HAMDTL17` variable and the `CHANGE` variable is empty.

Or could you give me a solution to address it, thank a lot!

**Comment by wolbersm** [comment]
Hi @gowerc 

I think @kaigu1990 wants to impute the raw `HAMDTL17` variable (not the `CHANGE` from baseline) but then still analyze the change. I am not sure what the exact use case for this is but from a pure implementation perspective, one way to implement this is via a custom analysis function (see the [advanced vignette](https://insightsengineering.github.io/rbmi/main/articles/advanced.html#custom-analysis-functions)) and use `I(HAMDTL17-BASVAL)` as the outcome in you analysis model.

**Comment by wolbersm** [comment]
Thanks @gowerc. 
If it is easy to add such a pre-processing hook, I feel this would be a nice-to-have (but not a critical) feature.

**Comment by wolbersm** [comment]
Yes, agree. Nice solution and agree the enhancement is not needed but we should add an example to the vignette (e.g. modify the code in Section 7 of the advanced vignette accordingly).
