### ISSUE TITLE
Verify compatibility of `rstan` dependent packages

### ISSUE THREAD

**Issue by nociale** [insightsengineering/rbmi#91]
@gowerc I think we should consider having a quick look at the required version of the packages that `rstantools::use_rstan()` has inserted in the DESCRIPTION file. For example, I have noticed that the description file requires version of `RcppParallel` `(>= 5.0.1)`. This version was not available on the Apollo server, so I relaxed `(>= 5.0.1)` to be  `(>= 5.0.0)`. The installation of `rbmi` and the call of its functions was ok also with version `5.0.0` of `RcppParallel`. I am wondering whether we should investigate more about such dependencies (if you think that this can be relevant for our package).

**Comment by gowerc** [comment]
No one ever got back to me. I am reluctant to reduce the Stan versions without knowing that its fine to do so. I am partially tempted to close this issue as a "wont fix" given the potentially risk to valid results if it induces complications that are not immediately visible.

**Comment by gowerc** [comment]
Just to add I've gone over all the rstan dependencies version thresholds and the highest date of availability requirement was June 2020.  This should cause no issues as our internal R 4.0.4 server will have a date cut of April 2021.
